name: Pull & Run from GitLab

on:
  schedule:
    - cron: "0 * * * *"   # Toutes les heures
  workflow_dispatch:

jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_LINK: ${{ secrets.GITLAB_LINK }}
      DISCORD_MANGA_WEBHOOK_URL: ${{ secrets.DISCORD_MANGA_WEBHOOK_URL }}
      DISCORD_MANWHA_WEBHOOK_URL: ${{ secrets.DISCORD_MANWHA_WEBHOOK_URL }}
      DISCORD_ANIME_WEBHOOK_URL: ${{ secrets.DISCORD_ANIME_WEBHOOK_URL }}

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: 🧪 Debug – Liste du dossier `.github/scripts/`
        run: |
          echo "Contenu de .github/scripts :"
          ls -l .github/scripts || echo "❌ Dossier scripts introuvable"
          echo "Contenu global du repo :"
          find . -type f

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 🚀 Pull & Run scraper
        run: bash .github/scripts/pull_and_run.sh
